# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
- name: 'hseeberger/scala-sbt'
  args:
  - 'sbt'
  - 'docker:publishLocal'
  waitFor: ['-']
