# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

- name: 'hseeberger/scala-sbt:8u222_1.3.5_2.13.1'
  args:
  - 'docker run'
  - '--privileged'
  - '-d docker:dind'
  waitFor: ['-']
