# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml
- name: 'gcr.io/gridcure-dev/sbt-docker:latest'
  args:
  - 'sbt'
  - 'docker:publish'
  waitFor: ['-']
